[package]
name = "chatbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.2"
tokio = "0.1.16"
tokio-channel = "0.1.0"
